# COBRA.jl - Tutorial

This tutorial serves as a quick start guide as well as an interactive reference for more advanced users.

Download the live notebook [here](https://github.com/opencobra/COBRA.jl/tree/master/docs/tutorial).

## Beginner's Guide

Should you not have any prior experience with Julia and/or Linux, please **read carefully** the [Beginner's Guide](http://opencobra.github.io/COBRA.jl/stable/cobratutorial.html). If you however feel that you are set to proceed with this tutorial, please consider the Beginner's Guide as a go-to reference in case you are running into any issues. If you see unusual behavior, you may consider reading the [FAQ section](http://opencobra.github.io/COBRA.jl/stable/faq.html).

In [91]:
# donwload the test model
include("$(Pkg.dir("COBRA"))/test/getTestModel.jl")
getTestModel()

# load the stoichiometric matrix S from a struct named model in the specified .mat file
model = loadModel("$(Pkg.dir("COBRA"))/test/ecoli_core_model.mat", "S", "model");

INFO: The ecoli_core model already exists.


LoadError: File "/home/laurent/.julia/v0.5/COBRA/test/ecoli_core_model.mat" does not exist and create was not specified

## Quick installation

Should you not already have the `COBRA.jl` package, you must first first follow the installation instructions [here](http://opencobra.github.io/COBRA.jl/).

> Please note that should you run this tutorial on an already configured system, the following lines will throw an error message.

Before running any function of `COBRA.jl`, it is necessary to include the `COBRA.jl` module:

In [92]:
using COBRA

## Quick help

Should you feel lost or don't know the meaning of certain input parameters, try typing a question mark at the Julia REPL followed by a keyword. For instance:

In [93]:
? distributedFBA

search: distributedFBA saveDistributedFBA



```
distributedFBA(model, solver, nWorkers, optPercentage, objective, rxnsList, strategy, rxnsOptMode, preFBA, saveChunks, resultsDir, logFiles, onlyFluxes)
```

Function to distribute a series of FBA problems across one or more workers that have been initialized using the `createPool` function (or similar).

# INPUTS

  * `model`:          An `::LPproblem` object that has been built using the `loadModel` function.                       All fields of `model` must be available.
  * `solver`:         A `::SolverConfig` object that contains a valid `handle` to the solver
  * `nWorkers`:       Number of workers as initialized using `createPool()` or similar

# OPTIONAL INPUTS

  * `optPercentage`:  Only consider solutions that give you at least a certain percentage of the optimal solution (default: 100%)
  * `objective`:      Objective ("min" or "max") (default: "max")
  * `rxnsList`:       List of reactions to analyze (default: all reactions)
  * `strategy`:       Number of the splitting strategy

      * 0: Blind splitting: default random distribution
      * 1: Extremal dense-and-sparse splitting: every worker receives dense and sparse reactions, starting from both extremal indices of the sorted column density vector
      * 2: Central dense-and-sparse splitting: every worker receives dense and sparse reactions, starting from the beginning and center indices of the sorted column density vector
  * `rxnsOptMode`:    List of min/max optimizations to perform:

      * 0: only minimization
      * 1: only maximization
      * 2: minimization & maximization [default: all reactions are minimized and maximized, i.e. `2+zeros(Int,length(model.rxns))]`
  * `preFBA`:         Solve the original FBA and add a percentage condition (Boolean variable, default: true for flux variability analysis FVA)
  * `saveChunks`:     Save the fluxes of the minimizations and maximizations in individual files on each worker (applicable for large models, default: false)
  * `resultsDir`:     Path to results folder (default is a `results` folder in the Julia package directory)
  * `logFiles`:       Boolean to write a solver logfile of each optimization (default: false)
  * `onlyFluxes`:     Save only minFlux and maxFlux if true and will return placeholders for `fvamin`, `fvamax`, `statussolmin`, or `statussolmax` (applicable for quick checks of large models, default: false)

# OUTPUTS

  * `minFlux`:        Minimum flux for each reaction
  * `maxFlux`:        Maximum flux for each reaction
  * `optSol`:         Optimal solution of the initial FBA (if `preFBA` set to `true`)
  * `fbaSol`:         Solution vector of the initial FBA (if `preFBA` set to `true`)
  * `fvamin`:         Array with flux values for the considered reactions (minimization) (if `onlyFluxes` set to `false`)     Note: `fvamin` is saved in individual `.mat` files when `saveChunks` is `true`.
  * `fvamax`:         Array with flux values for the considered reactions (maximization) (if `onlyFluxes` set to `false`)     Note: `fvamax` is saved in individual `.mat` files when `saveChunks` is `true`.
  * `statussolmin`:   Vector of solution status for each reaction (minimization) (if `onlyFluxes` set to `false`)
  * `statussolmax`:   Vector of solution status for each reaction (maximization) (if `onlyFluxes` set to `false`)

# EXAMPLES

  * Minimum working example

```julia
julia> minFlux, maxFlux = distributedFBA(model, solver)
```

  * Full input/output example

```julia
julia> minFlux, maxFlux, optSol, fbaSol, fvamin, fvamax, statussolmin, statussolmax = distributedFBA(model, solver, nWorkers=nWorkers, logFiles=true)
```

  * Save only the fluxes

```julia
julia> minFlux, maxFlux = distributedFBA(model, solver, preFBA=true, saveChunks=false, onlyFluxes=true)
```

  * Save flux vectors in files

```julia
julia> minFlux, maxFlux, optSol, fbaSol, fvamin, fvamax, statussolmin, statussolmax = distributedFBA(model, solver)
```

See also: `preFBA!()`, `splitRange()`, `buildCobraLP()`, `loopFBA()`, or `fetch()`


## Installation check and package testing

Please make sure that you have a working installation of `MathProgBase.jl` and at least one of the supported solvers. You may find further information [here](http://mathprogbasejl.readthedocs.io/en/latest/). You may run the following in order to be sure and check your system's configuration. 

You can find further information on how to install other supported solvers, such as `CPLEX`, `CLP`, `Gurobi`, or `Mosek` [here](https://github.com/JuliaOpt).

In [94]:
# loads the functions to check your setup
include("$(Pkg.dir("COBRA"))/src/checkSetup.jl") 

# list your installed packages
packages = checkSysConfig()

# clear the workspace of loaded packages
workspace()


 >> Checking the system's configuration ...

Clp is installed.
GLPKMathProgInterface is installed.
Gurobi is installed.
CPLEX is installed.
Package Mosek is not installed. In order to use Mosek, you must first run `Pkg.add("Mosek")`

 >> Done. 4 solvers are installed and ready to use.


You may, at any time, check the integrity of the `COBRA.jl` package by running:

```Julia
Pkg.test("COBRA")
```

The code has been benchmarked against the `fastFVA` implementation [[3](#References-1)]. A test model `ecoli_core_model.mat` [[4](#References-1)] can be used to pre-compile the code and is available in the `/test` folder. The modules and solvers are correctly installed when all tests pass without errors (warnings may appear).

## Adding local workers

The connection functions are given in `connect.jl`, which, if a parallel version is desired, must be included separately:

In [95]:
include("$(Pkg.dir("COBRA"))/src/connect.jl")

You may add local workers as follows:

In [96]:
# specify the total number of parallel workers
nWorkers = 4 

# create a parallel pool
workersPool, nWorkers = createPool(nWorkers) 

4 workers already connected. No further workers to connect.


INFO: Parallel version - Connecting the 4 workers ...


([2,3,4,5],4)

The IDs of the respective workers are given in `workersPool`, and the number of local workers is stored in `nWorkers`.

In order to be able to use the `COBRA` module on all connected workers, you must invoke (the `Compat` package may throw errors):

In [97]:
using COBRA

## Define and change the COBRA solver

Before the COBRA solver can be defined, the solver parameters and configuration must be loaded after having set the `solverName` (solver must be installed):

- `:GLPKMathProgInterface`
- `:CPLEX`
- `:Clp`
- `:Gurobi`
- `:Mosek`

In [98]:
# specify the solver name
solverName = :GLPKMathProgInterface

# include the solver configuration file
include("$(Pkg.dir("COBRA"))/config/solverCfg.jl")

# change the COBRA solver
solver = changeCobraSolver(solverName, solParams)

COBRA.SolverConfig("GLPKMathProgInterface",GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP(true,:Simplex,Any[]))

where `solParams` is an array with the definition of the solver parameters.

## Load a COBRA model

As a test and as an example, the *E.coli* core model may be loaded as:

In [99]:
# download the ecoli_core_model
include("$(Pkg.dir("COBRA"))/test/getTestModel.jl")
getTestModel()

# load the stoichiometric matrix S from a struct named model in the specified .mat file
model = loadModel("ecoli_core_model.mat", "S", "model");

INFO: The ecoli_core model already exists.
INFO: The model objective is set to be maximized.
INFO: All constraints assumed equality constaints.


where `S` is the name of the field of the stoichiometric matrix and `model` is the name of the model. Note the semicolon that suppresses the ouput of `model`.


## Flux Balance Analysis (FBA)

In order to run a flux balance analysis (FBA), `distributedFBA` can be invoked with only 1 reaction and without an extra condition:

In [100]:
# set the reaction list (only one reaction)
rxnsList = 13

# select the reaction optimization mode
#  0: only minimization
#  1: only maximization
#  2: maximization and minimization
rxnsOptMode = 1

# launch the distributedFBA process with only 1 reaction on 1 worker
# distributedFBA(model, solver, nWorkers, optPercentage, objective, rxnsList, strategy, preFBA, rxnsOptMode)
minFlux, maxFlux  = distributedFBA(model, solver, nWorkers=1, optPercentage=90.0, rxnsList=rxnsList,rxnsOptMode=rxnsOptMode);


 >> Size of stoichiometric matrix: (72, 95)

preFBA! [osenseStr = max]: FBAobj = 0.8739215069684303, optPercentage = 90.0, objValue = optPercentage * FBAobj = 0.7865289, norm(fbaSol) = 106.83731553000716.

Original FBA solved. Solution time: 0.501013994216919 s.

 >> Only 1 reaction of 95 will be solved (~ 1.0526315789473684 %).

 -- Maximization (iRound = 1). Block 1 [1/95].


where the reaction number `13` is solved. Note that the no extra conditions are added to the model (last function argument is `false`). The minimum flux and maximum flux can hence be listed as:

In [101]:
maxFlux[rxnsList]

0.8739215069684305

## Flux Variability Analysis (FVA)

In order to run a common flux variability analysis (FVA), `distributedFBA` can be invoked with all reactions as follows:

In [102]:
# launch the distributedFBA process with all reactions
# distributedFBA(model, solver, nWorkers, optPercentage, objective, rxnsList, strategy, preFBA, rxnsOptMode)
minFlux, maxFlux, optSol, fbaSol, fvamin, fvamax = distributedFBA(model, solver, nWorkers=4, optPercentage=90.0);


 >> Size of stoichiometric matrix: (73, 95)

preFBA! [osenseStr = max]: FBAobj = 0.8739215069684305, optPercentage = 90.0, objValue = optPercentage * FBAobj = 0.7865289, norm(fbaSol) = 106.83731553000717.

Original FBA solved. Solution time: 0.0019719600677490234 s.

 >> All 95 reactions of the model will be solved (100 %).

Average load per worker: 24 reactions (4 workers).
Splitting strategy is 0.

	From worker 5:	 -- Minimization (iRound = 0). Block 5 [23/95].
	From worker 4:	 -- Minimization (iRound = 0). Block 4 [24/95].
	From worker 5:	 -- Maximization (iRound = 1). Block 5 [23/95].
	From worker 4:	 -- Maximization (iRound = 1). Block 4 [24/95].
	From worker 2:	 -- Minimization (iRound = 0). Block 2 [24/95].
	From worker 3:	 -- Minimization (iRound = 0). Block 3 [24/95].
	From worker 2:	 -- Maximization (iRound = 1). Block 2 [24/95].
	From worker 3:	 -- Maximization (iRound = 1). Block 3 [24/95].


The optimal solution of the original FBA problem can be retrieved with:

In [103]:
optSol

0.8739215069684305

The corresponding solution vector `maxFlux` of the original FBA that is solved with:

In [104]:
fbaSol

95-element Array{Float64,1}:
 -1.24283e-29
  0.0        
 -8.0942e-29 
  6.00725    
  6.00725    
 -0.0        
  0.0        
  5.06438    
 -0.0        
 -1.24283e-29
  8.39       
 45.514      
  0.873922   
  ⋮          
 -0.0        
  2.67848    
 -2.2815     
 -0.0        
  0.0        
  5.06438    
 -5.06438    
  1.49698    
  0.0        
  1.49698    
  1.1815     
  7.47738    

The minimum and maximum fluxes of each reaction are in:

In [105]:
maxFlux

95-element Array{Float64,1}:
   -2.9243e-29 
    0.0        
   -8.87161e-29
    8.89453    
    8.89453    
    0.0        
   17.1611     
    8.04594    
    0.0        
   -2.9243e-29 
   25.5511     
   59.3811     
    0.873922   
    ⋮          
    0.0        
   15.5265     
   -0.565357   
   22.8815     
   22.8815     
 1000.0        
   -1.00265e-28
    7.90523    
   37.0422     
    7.90523    
    7.62129    
    9.21764    

The flux vectors of all the reactions are stored in `fvamin` and `fvamax`.

In [106]:
fvamin

95×95 Array{Float64,2}:
 -2.54238      -2.54238       2.19322e-30  …  -1.0235e-29   -2.23709e-28
 -2.54238      -2.54238       0.0              0.0           0.0        
 -2.2865e-31   -2.2865e-31   -3.81358         -4.29861e-29   1.36458e-27
  4.75567       4.75567       3.23024          7.8033        0.848586   
  4.75567       4.75567       3.23024          7.8033        0.848586   
 -0.0          -0.0          -3.81358      …  -0.0          -0.0        
  0.0           0.0           0.0              0.0           3.97558    
  3.90709       3.90709       2.38166          6.87133       0.0        
 -0.0          -0.0          -0.0             -0.0          -0.0        
  8.04182e-30   8.04182e-30   2.19322e-30     -1.0235e-29   -2.23709e-28
  8.39          8.39          8.39         …   8.39          8.39       
 40.5609       40.5609       38.527           41.3535       54.893      
  0.786529      0.786529      0.786529         0.863813      0.786529   
  ⋮                        

In [107]:
fvamax

95×95 Array{Float64,2}:
 -2.9243e-29   -2.9243e-29   -2.9243e-29   …  -2.23709e-28  -2.9243e-29 
  0.0           0.0           0.0              0.0           0.0        
 -8.87161e-29  -8.87161e-29  -8.87161e-29      1.36458e-27  -8.87161e-29
  8.89453       8.89453       8.89453          0.848586      8.89453    
  8.89453       8.89453       8.89453          0.848586      8.89453    
 -0.0          -0.0          -0.0          …  -0.0          -0.0        
  0.0           0.0           0.0              3.97558       0.0        
  8.04594       8.04594       8.04594          0.0           8.04594    
 -0.0          -0.0          -0.0             -0.0          -0.0        
 -2.9243e-29   -2.9243e-29   -2.9243e-29      -2.23709e-28  -2.9243e-29 
  8.39          8.39          8.39         …   8.39          8.39       
 38.8959       38.8959       38.8959          54.893        38.8959     
  0.786529      0.786529      0.786529         0.786529      0.786529   
  ⋮                        

## Distributed FBA of distinct reactions

You may now input several reactions with various `rxnsOptMode` values to run specific optimization problems.

In [108]:
rxnsList = [1; 18; 10; 20:30; 90; 93; 95]
rxnsOptMode = [0; 1; 2; 2+zeros(Int, length(20:30)); 2; 1; 0]

# run only a few reactions with rxnsOptMode and rxnsList
# distributedFBA(model, solver, nWorkers, optPercentage, objective, rxnsList, strategy, preFBA, rxnsOptMode)
minFlux, maxFlux, optSol, fbaSol, fvamin, fvamax, statussolmin, statussolmax = distributedFBA(model, solver);


 >> Size of stoichiometric matrix: (74, 95)

The optPercentage is higher than 90. The solution process might take longer than expected.

preFBA! [osenseStr = max]: FBAobj = 0.8739215069684305, optPercentage = 100.0, objValue = optPercentage * FBAobj = 0.873921, norm(fbaSol) = 106.83731553000717.

Original FBA solved. Solution time: 0.002162933349609375 s.

 >> All 95 reactions of the model will be solved (100 %).

 -- Minimization (iRound = 0). Block 1 [95/95].
 -- Maximization (iRound = 1). Block 1 [95/95].


Note that the reactions can be input as an unordered list.

## Save the variables

You can save the output of `distributedFBA` by using:

In [109]:
saveDistributedFBA("results.mat")

Saving minFlux (T:> Array{Float64,1}) ...Done.
Saving maxFlux (T:> Array{Float64,1}) ...Done.
Saving optSol (T:> Float64) ...Done.
Saving fbaSol (T:> Array{Float64,1}) ...Done.
Saving fvamin (T:> Array{Float64,2}) ...Done.
Saving fvamax (T:> Array{Float64,2}) ...Done.
Saving statussolmin (T:> Array{Float64,1}) ...Done.
Saving statussolmax (T:> Array{Float64,1}) ...Done.
Saving rxnsList (T:> Array{Int64,1}) ...Done.
All available variables saved to results.mat.


## References

1. [B. O. Palsson. Systems Biology: Constraint-based Reconstruction and Analysis. Cambridge University Press, NY, 2015.](http://www.cambridge.org/us/academic/subjects/life-sciences/genomics-bioinformatics-and-systems-biology/systems-biology-constraint-based-reconstruction-and-analysis?format=HB)
2. [Schellenberger, J. et al. COBRA Toolbox 2.0. 05 2011.](https://github.com/opencobra/cobratoolbox)
3. [Steinn, G. et al. Computationally efficient flux variability analysis. BMC Bioinformatics, 11(1):1–3, 2010.](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-489)
4. [Orth, J. et al. Reconstruction and use of microbial metabolic networks: the core escherichia coli metabolic model as an educational guide. EcoSal Plus, 2010.](http://gcrg.ucsd.edu/Downloads/EcoliCore)
